######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 18 16:16:41 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += new.h
SOURCES += new.cpp tahoon.cpp
